site_name: My Docs
theme: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            members_order: source
            show_source: false
            extensions:
              - griffe_inherited_docstrings
